apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"  
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"     
          ports:
            - containerPort: {{ .Values.mysql.port }}
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: mysql-temp-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-temp-storage
          emptyDir: {}
